#!/bin/bash
# Add default user and give them sudo powers

function check-user-exists()
{
    local username=$1

    ret=$($CHROOTCMD id ${username})
    echo "${ret}"
}

function add-user()
{
    local username=$1

    ret=$(check-user-exists ${username})
    if [ -n "${ret}" ] ; then
        echo "User '${username}' exists.  Skipping add-user"
        return
    fi

    $CHROOTCMD adduser --disabled-password --gecos \"\" ${username}
    echo "${username}:${username}" | $CHROOTCMD chpasswd
}

function add-admin()
{
    local username=$1
    local groups="sudo,root,adm,utmp"

    #check-user-exists ${username}

    ret=$(add-user ${username})
    if [ -n "${ret}" ] ; then
        echo "User '${username}' exists.  Skipping add-admin"
        #return
    fi

    echo "Add '${username}' to sudo group."
    $CHROOTCMD usermod -a -G ${groups} ${username}

    #! Add paths users profile.
    local profile="/home/${username}/.profile"

    #! Add path for EFD executables.
    $CHROOTCMD bash -c "echo >> ${profile}"
    $CHROOTCMD bash -c "echo 'PATH=\$PATH:/opt/sbin' >> ${profile}"

    #! Add path for EFD Production executables.
    $CHROOTCMD bash -c "echo >> ${profile}"
    $CHROOTCMD bash -c "echo 'PATH=\$PATH:/opt/sbin/prod_test' >> ${profile}"
}

add-admin sepladmin

add-user sepluser

add-admin efdadmin

add-user efduser
