#!/bin/bash

## backup original conf file and replace with a SEPL customised file.
${CHROOTCMD} cp -a /etc/chrony/chrony.conf      /etc/chrony/chrony_ORIG.conf
${CHROOTCMD} cp    /etc/chrony/chrony_SEPL.conf /etc/chrony/chrony.conf

## Enable chrony systemd service.
$CHROOTBINDCMD systemctl enable chrony

