#!/bin/bash

#! script to setup/modify the cron defaults file.

#! backup original conf file and replace with a SEPL customised file.
${CHROOTCMD} cp -a /etc/default/cron      /etc/default/cron_ORIG
${CHROOTCMD} cp    /etc/default/cron_SEPL /etc/default/cron

#! Enable cron systemd service.
${CHROOTBINDCMD} systemctl enable cron
