#!/bin/bash

#! script to setup/modify the cron config file.

#! backup original conf file and replace with a SEPL customised file.
${CHROOTCMD} cp -a /etc/default/cron.conf      /etc/default/cron_ORIG.conf
${CHROOTCMD} cp    /etc/default/cron_SEPL.conf /etc/default/cron.conf

#! Enable cron systemd service.
${CHROOTBINDCMD} systemctl enable cron

