#!/bin/bash

#!============================================================================
#!
#! script to setup/modify the gpsd config file.
#!
#!============================================================================

#! backup original defaults file and replace with a SEPL customised file.
${CHROOTCMD} cp -a /etc/default/gpsd        /etc/default/gpsd_ORIG
${CHROOTCMD} cp    /etc/default/gpsd_SEPL   /etc/default/gpsd


#! Enable gpsd systemd service at startup
$CHROOTBINDCMD systemctl enable gpsd
