#!/bin/bash

## Install linux image from zynq_IND build directory.

#DEB_IMAGE="linux-image-4.0.0-ge2aa738-dirty_4.0.0-ge2aa738-dirty-1_armhf.deb"

#DTB_IMAGE="zynq-IND.dtb"

##
## Install linux debian package.
##
#echo "Installing '${DEB_IMAGE}' ..."
#$CHROOTCMD dpkg -i "${HOSTFS_DEB_IMAGE}"

##
## Setup uImage symlink.
##
#$CHROOTCMD bash -c 'cd /boot && ln -sf $(ls -1rt uImage-* | tail -n 1) uImage'

##
## Install device tree.
##
#$CHROOTCMD cp "${HOSTFS_DTB_IMAGE}" /boot/
#cp ${DTB_BUILD_DIR)/${DTB_IMAGE} {BRICKSTRAP_BUILD_DIR}/boot/
#$CHROOTCMD bash -c 'cd /boot && ln -sf zynq-IND.dtb ind.dtb'

