#!/bin/bash

#!============================================================================
#!
#!  Install `selectors2` python module (not available as a Debian package)
#!
#!============================================================================

PY_MOD="selectors2-2.0.1-py2.py3-none-any.whl"

HOST_SRC_DIR="/host-rootfs/${BOARDDIR}/third-party"

HOST_PY_MOD="${HOST_SRC_DIR}/${PY_MOD}"

#!
#! Debug info.
#!
#echo "PY_MOD = '${PY_MOD}'"
#echo "HOST_SRC_DIR = '${HOST_SRC_DIR}'"
#echo "HOST_PY_MOD = '${HOST_PY_MOD}'"

#!
#! Install Python module.
#!
echo "Installing '${PY_MOD}' ..."
${CHROOTCMD} pip install --upgrade ${HOST_PY_MOD}
